AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Style/SingleLineMethods:
  Exclude:
    - 'test/**/*'

Lint/MissingSuper:
  Exclude:
    - 'lib/problems/old_entities/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/ParameterLists:
  Exclude:
    - 'lib/problems/old_entities/numbered_solution_for_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/components/action_with_arguments_test.rb'

Metrics/ClassLength:
  Exclude:
    - 'test/components/action_with_arguments_test.rb'
